"""pygrits — evidence-grounded nodes on PROV-O."""

__version__ = "0.5.0"

from pygrits.canonical import (
    canonical_bytes_for_instance,
    canonical_hash_bytes,
    canonical_hash_instance,
    compute_content_hash,
    stamp,
    verify_content_reference,
)
from pygrits.core import (
    Activity,
    ActivityType,
    BboxLocator,
    CharRangeLocator,
    CompositeLocator,
    Confidence,
    ConfidenceBasis,
    ContentReference,
    Entity,
    EvidenceLabel,
    EvidenceLink,
    EvidenceRecord,
    FileRegionLocator,
    Grit,
    HashMode,
    LineRangeLocator,
    Locator,
    NegativeEvidenceRecord,
    NegativeResult,
    NotesOnlyScope,
    ReviewState,
    Scope,
    SequencePositionLocator,
    TableCellLocator,
    ViewpointDirective,
)
from pygrits.resources import json_schema_path, schema_path, viewpoint_json_schema_path, viewpoint_schema_path
from pygrits.validate import BundleValidationError, validate_bundle

__all__ = [
    "__version__",
    "Grit",
    "Entity",
    "Activity",
    "EvidenceRecord",
    "NegativeEvidenceRecord",
    "ViewpointDirective",
    "EvidenceLink",
    "ContentReference",
    "Scope",
    "NotesOnlyScope",
    "Locator",
    "CharRangeLocator",
    "LineRangeLocator",
    "BboxLocator",
    "SequencePositionLocator",
    "TableCellLocator",
    "FileRegionLocator",
    "CompositeLocator",
    "Confidence",
    "HashMode",
    "ActivityType",
    "EvidenceLabel",
    "ReviewState",
    "NegativeResult",
    "ConfidenceBasis",
    "canonical_hash_instance",
    "canonical_hash_bytes",
    "canonical_bytes_for_instance",
    "compute_content_hash",
    "stamp",
    "verify_content_reference",
    "validate_bundle",
    "BundleValidationError",
    "schema_path",
    "json_schema_path",
    "viewpoint_schema_path",
    "viewpoint_json_schema_path",
]
